### PR TITLE
Remove bubleify dependency

### LINKED ISSUE #9: Move or remove bubleify dependency
`bubleify` is listed in the production dependencies of this module. This seems to be causing unnecessary bloat when this module is depended upon by other packages.

At the very least, it should be moved to `devDependencies` but after looking a little deeper, this module doesn't appear to even use `bubleify`! Let's just remove it for now.

### PR DESCRIPTION
**Pull request by sirlancelot**
Fixes #9 

`bubleify` doesn't appear to be used and is listed as a production dependency which is bloating the `npm install` process for dependent projects.

### CODE REVIEW

**Comment by sirlancelot** [comment]
Any thoughts, @jimdebeer? Would you be able to incorporate this and submit a new version to npm?

**Comment by jimdebeer** [comment]
im afk atm but willdo this tmrw!

**Comment by jimdebeer** [comment]
published v1.0.8

**Comment by sirlancelot** [comment]
Thanks, @jimdebeer!

**Pull request merged**
