### PR TITLE
'const length = val.length' breaking build #6'

### PR DESCRIPTION
**Pull request by marioagarcia**
Changed the use of es6 const for var so that all node versions can work with it.

### CODE REVIEW

**Comment by NareshBanala** [comment]
Any ETA on when this will be merged.

**Comment by jimdebeer** [comment]
traveling now merge it in 2 hrs

**Comment by jimdebeer** [comment]
there it is, publishing to npm and adding travis build target 0.12

**Comment by jimdebeer** [comment]
version 1.0.7

**Comment by NareshBanala** [comment]
I still don't see 1.0.7 version in https://www.npmjs.com/package/is-number-like

**Pull request merged**
